services:
  postgres:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
  backend:
    build:
      context: ../backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - BIND_ADDRESS=0.0.0.0:9000
    env_file: .env
  frontend:
    build:
      context: ../frontend
    restart: unless-stopped
  gateway:
    image: nginx
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8080"
    depends_on:
      - postgres
volumes:
  database:
